### ISSUE TITLE
Not working why?

### ISSUE THREAD

**Issue by YumaYamamoto** [A200K/TeamSpeak3_Badge_Spoofing#1]
So I just tried to give me some badges around 6-7 and I did put it into the plugins folder but its not working why?

**Comment by YumaYamamoto** [comment]
I just saw you can just have 3 icons? I have already two without this so I just can use one with that plugin?

I just have this two icons, even when I just put the E3 code into the main.cpp http://prntscr.com/kldavi

**Comment by A200K** [comment]
This plugin will override your badges, you can set these to any badge you want. If you want to keep your old badges you need to add their ids as well. And yes, you can have a maximum of 3 badtes at the same time.

**Comment by A200K** [comment]
Please show me your main.cpp line where you send the badge ids

**Comment by YumaYamamoto** [comment]
SendCommandToServer( "clientupdate client_badges=Overwolf=0:badges=935e5a2a-954a-44ca-aa7a-55c79285b601" );

So I have to add the gamescom 2018 icon and the other icon too right?

**Comment by A200K** [comment]
As I said, this command will override your badges. To get the other ones you had on your screenshot too (the Gamescom 2018 and TS early adopter one), your command should look like

SendCommandToServer( "clientupdate client_badges=Overwolf=0:badges=4eef1ecf-a0ea-423d-bfd0-496543a00305,64221fd1-706c-4bb2-ba55-996c39effa79,935e5a2a-954a-44ca-aa7a-55c79285b601" );
