### ISSUE TITLE
Is it still working on TS Client v3.2.2  (17.09.2018 12:01:05)?

### ISSUE THREAD

**Issue by mthrim** [A200K/TeamSpeak3_Badge_Spoofing#2]
Hi, I compiled the project with Visual Studio 2017, copied and activated the dll in TS (Client v3.2.2), no errors so far. But no matter which badge code I use, it doesn't work. The server version is 3.3.0 btw.
Any ideas? Thanks!
https://i.imgur.com/5q3MbRU.png

**Comment by mthrim** [comment]
> Hi, I compiled the project with Visual Studio 2017, copied and activated the dll in TS (Client v3.2.2), no errors so far. But no matter which badge code I use, it doesn't work. The server version is 3.3.0 btw.
> Any ideas? Thanks!
> https://i.imgur.com/5q3MbRU.png

**Comment by A200K** [comment]
Tested on a 3.3.1 server and 3.2.2 client, it indeed still works for me. Since you closed this issue, may I know how you solved it?

**Comment by mthrim** [comment]
Unfortunately, I can't reproduce why it didn't work. I reinstalled Teamspeak, after that it just worked.
Thanks for the reply though!
