### ISSUE TITLE
Badge spoofing patched

### ISSUE THREAD

**Issue by Suphax** [A200K/TeamSpeak3_Badge_Spoofing#4]
Just letting you know this was patched by TeamSpeak on 18th June with `3.3.0` as they now check if a user owns the badge.

> In previous versions of our client and/or server, it was possible to inject fake badge data. We've eliminated this problem with a new feature called Signed-Badges. If a user configures a badge in his/her myTeamSpeak account settings, the server will now validate this info and only show the badge icon if the user really possesses it.

https://forum.teamspeak.com/threads/140245-Release-TeamSpeak-Client-3-3-0

**Comment by A200K** [comment]
Thank you for letting me know.
